// <auto-generated>
//     Generated from docs/PRESETS.md by scripts/apply-presets.sh - do not edit.
//     Change a preset column in docs/PRESETS.md and re-run the script; hand
//     edits here are overwritten and CI's --check fails on them.
// </auto-generated>

using System;

namespace Fairoots.Core.Presets
{
    /// <summary>
    /// The raw per-preset numbers, one method per setting, indexed by presets
    /// 1-4 only. <see cref="PresetCatalog"/> is the documented front door onto
    /// this - it maps <see cref="PresetId.Custom"/> to a safe key first and is
    /// where the reasoning for each row lives. Game-facing code should read
    /// neither directly: it wants <c>PluginConfig</c>'s <c>Effective*</c>
    /// accessors, which fold in the player's override and host authority.
    /// </summary>
    public static class PresetValues
    {
        private static T Pick<T>(PresetId preset, T subtle, T balanced, T generous, T tame)
        {
            switch (preset)
            {
                case PresetId.Subtle: return subtle;
                case PresetId.Balanced: return balanced;
                case PresetId.Generous: return generous;
                case PresetId.Tame: return tame;
                default:
                    throw new ArgumentOutOfRangeException(
                        nameof(preset),
                        preset,
                        "PresetValues is indexed by presets 1-4 only - map Custom first (PresetCatalog does).");
            }
        }

        // --- Spore-Bombs ---
        public static double SporeBombCullFraction(PresetId preset) =>
            Pick(preset, 0.00, 0.05, 0.15, 0.25);
        public static bool EnableFoliageRemoval(PresetId preset) =>
            Pick(preset, true, true, true, true);
        public static double SporeBombTriggerRadiusMultiplier(PresetId preset) =>
            Pick(preset, 0.90, 0.75, 0.70, 0.60);
        public static double SporeBombKnockbackMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.90, 0.70, 0.50);
        public static double SporeBombScreenshakeRangeCapMeters(PresetId preset) =>
            Pick(preset, 75.0, 75.0, 50.0, 50.0);
        public static double SporeBombVfxCountMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.75, 0.50, 0.35);
        public static double SporeBombTriggerHeightMultiplier(PresetId preset) =>
            Pick(preset, 0.90, 0.804, 0.804, 0.804);
        public static double SporeBombSporeAreaRadiusMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 1.00, 1.00);

        // --- Spore-Areas ---
        public static double SporeAreaRemovalFraction(PresetId preset) =>
            Pick(preset, 0.00, 0.00, 0.20, 0.35);
        public static double SporeAreaRadiusMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.90, 0.80);
        public static double SporeAreaStatusRateMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.90, 0.80);
        public static bool EnableCoverMouth(PresetId preset) =>
            Pick(preset, true, true, true, true);
        public static float CoverMouthStaminaPerSecond(PresetId preset) =>
            Pick(preset, 0.04f, 0.03f, 0.02f, 0.01f);

        // --- Spores ---
        public static double SporeClearTimeMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.80, 0.75, 0.65);
        public static double SporeBuildUpMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 1.00, 1.00);

        // --- Creatures ---
        public static double ZombieSpeedMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.90, 0.80, 0.65);
        public static double BeetleSpeedMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.90, 0.80);
        public static double BeetleKnockbackMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.80, 0.65, 0.50);
        public static double CreatureRagdollMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 0.85, 0.65, 0.40);
        public static bool ZombieDeaggroEnabled(PresetId preset) =>
            Pick(preset, false, true, true, true);
        public static double ZombieDeaggroMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.85, 0.75);
        public static double BeetleDeaggroMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.90, 0.80);
        public static double ZombieKnockoutSeconds(PresetId preset) =>
            Pick(preset, 1.0, 2.0, 3.0, 4.0);
        public static double BeetleKnockoutSeconds(PresetId preset) =>
            Pick(preset, 2.0, 3.0, 4.0, 4.0);
        public static double CreatureKnockoutMinThrowSpeed(PresetId preset) =>
            Pick(preset, 38.0, 36.0, 34.0, 32.0);
        public static double CreatureKnockoutMaxThrowDistance(PresetId preset) =>
            Pick(preset, 10.0, 12.0, 13.0, 15.0);
        public static bool BlowgunAffectsCreatures(PresetId preset) =>
            Pick(preset, true, true, true, true);
        public static double BlowgunCreatureStunSeconds(PresetId preset) =>
            Pick(preset, 30.0, 45.0, 60.0, 60.0);
        public static double ZombieWindMultiplier(PresetId preset) =>
            Pick(preset, 1.2, 1.4, 1.5, 1.6);
        public static double BeetleWindSusceptibility(PresetId preset) =>
            Pick(preset, 0.25, 0.40, 0.60, 0.80);

        // --- Wind ---
        public static bool WindBackpackAlwaysImmune(PresetId preset) =>
            Pick(preset, true, true, true, true);
        public static double WindForceMultiplier(PresetId preset) =>
            Pick(preset, 0.95, 0.95, 0.90, 0.85);
        public static double WindGustDurationMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.00, 0.90, 0.90);
        public static double WindItemForceMultiplier(PresetId preset) =>
            Pick(preset, 0.70, 0.60, 0.40, 0.20);
        public static double WindObstacleOcclusionRangeMultiplier(PresetId preset) =>
            Pick(preset, 1.00, 1.20, 1.30, 1.50);
        public static double WindFallCameraDampenClamp(PresetId preset) =>
            Pick(preset, 0.20, 0.35, 0.55, 0.75);
        public static float WindRecentForceWindowSeconds(PresetId preset) =>
            Pick(preset, 1.0f, 1.5f, 2.0f, 2.5f);
        public static bool PreventWindRagdoll(PresetId preset) =>
            Pick(preset, true, true, true, true);
        public static bool ClimbSheltersFromWind(PresetId preset) =>
            Pick(preset, false, true, true, true);
        public static double ClimbWindSpeedMultiplier(PresetId preset) =>
            Pick(preset, 0.85, 0.90, 0.93, 0.96);
        public static double ClimbWindUpwardSpeedMultiplier(PresetId preset) =>
            Pick(preset, 0.80, 0.85, 0.89, 0.94);
        public static double ClimbWindIntoWindSpeedMultiplier(PresetId preset) =>
            Pick(preset, 0.80, 0.85, 0.89, 0.94);
        public static float ClimbShelterGraceSeconds(PresetId preset) =>
            Pick(preset, 0.4f, 0.5f, 0.5f, 0.6f);
        public static double ClimbWindGraceForceMultiplier(PresetId preset) =>
            Pick(preset, 0.25, 0.15, 0.12, 0.10);
    }
}
