// <auto-generated>
//     Generated from docs/PRESETS.md by scripts/apply-presets.sh - do not edit.
//     Change a value in docs/PRESETS.md's "Default" column and re-run the
//     script; hand edits here are overwritten and CI's --check fails on them.
// </auto-generated>

namespace Fairoots.Core
{
    /// <summary>
    /// The value every Fairoots <em>balance</em> config entry is bound with -
    /// every setting in the five gameplay sections. Generated from
    /// docs/PRESETS.md, which documents the rule these encode: <b>every default
    /// is the vanilla value</b>, so Custom-preset-plus-untouched-settings plays
    /// exactly like unmodded PEAK. The one documented exception, gated parameters,
    /// is marked in the table. <c>General</c> and <c>Debug</c> are not balance
    /// values and are not generated - those defaults are literals in
    /// <c>PluginConfig</c>.
    /// </summary>
    public static class ConfigDefaults
    {
        // --- Spore-Bombs ---
        public const double SporeBombCullFraction = 0.0;
        public const bool EnableFoliageRemoval = false;
        public const double SporeBombTriggerRadiusMultiplier = 1.0;
        public const double SporeBombKnockbackMultiplier = 1.0;
        public const double SporeBombScreenshakeRangeCapMeters = 0.0;
        public const double SporeBombVfxCountMultiplier = 1.0;
        public const double SporeBombTriggerHeightMultiplier = 1.0;
        public const double SporeBombSporeAreaRadiusMultiplier = 1.0;
        public const bool CoverMouthBlocksSporeBombs = false;

        // --- Spore-Areas ---
        public const bool DisableSporeAreas = false;
        public const double SporeAreaRemovalFraction = 0.0;
        public const double SporeAreaRadiusMultiplier = 1.0;
        public const double SporeAreaStatusRateMultiplier = 1.0;
        public const bool EnableCoverMouth = false;
        public const float CoverMouthStaminaPerSecond = 0.03f;

        // --- Spores ---
        public const double SporeClearTimeMultiplier = 1.0;
        public const double SporeBuildUpMultiplier = 1.0;

        // --- Creatures ---
        public const bool DisableZombies = false;
        public const bool DisableBeetles = false;
        public const bool DisableSpiders = false;
        public const double ZombieSpeedMultiplier = 1.0;
        public const double BeetleSpeedMultiplier = 1.0;
        public const double BeetleKnockbackMultiplier = 1.0;
        public const double CreatureRagdollMultiplier = 1.0;
        public const bool ZombieDeaggroEnabled = false;
        public const double ZombieDeaggroMultiplier = 1.0;
        public const double BeetleDeaggroMultiplier = 1.0;
        public const double ZombieKnockoutSeconds = 0.0;
        public const double BeetleKnockoutSeconds = 0.0;
        public const double CreatureKnockoutMinThrowSpeed = 36.0;
        public const double CreatureKnockoutMaxThrowDistance = 12.0;
        public const bool BlowgunAffectsCreatures = false;
        public const double BlowgunCreatureStunSeconds = 45.0;
        public const double ZombieWindMultiplier = 1.0;
        public const double BeetleWindSusceptibility = 0.0;

        // --- Wind ---
        public const bool DisableWindEntirely = false;
        public const bool WindBackpackAlwaysImmune = false;
        public const double WindForceMultiplier = 1.0;
        public const double WindGustDurationMultiplier = 1.0;
        public const double WindItemForceMultiplier = 1.0;
        public const double WindObstacleOcclusionRangeMultiplier = 1.0;
        public const double WindFallCameraDampenClamp = 0.0;
        public const float WindRecentForceWindowSeconds = 1.5f;
        public const bool PreventWindRagdoll = false;
        public const bool ClimbSheltersFromWind = false;
        public const double ClimbWindSpeedMultiplier = 1.0;
        public const double ClimbWindUpwardSpeedMultiplier = 1.0;
        public const double ClimbWindIntoWindSpeedMultiplier = 1.0;
        public const float ClimbShelterGraceSeconds = 0.5f;
        public const double ClimbWindGraceForceMultiplier = 1.0;
    }
}
